on:
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"

jobs:
  check_changes:
    runs-on: ubuntu-latest
    name: "Check that changes is described"
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install towncrier
        run: pip install towncrier

      - name: "Check changelog"
        run: towncrier check --compare-with ${{ github.head_ref }}

      - if: "failure()"
        run: echo "FAILED"
      - if: "success()"
        run: echo "PASS"
